# Generated by Django 4.2.5 on 2024-08-14 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('num_of_students', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('assigned_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='core.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('guardian_full_name', models.CharField(max_length=255)),
                ('guardian_phone_number', models.IntegerField()),
                ('guardian_relation', models.CharField(max_length=25)),
                ('fees_paid', models.FloatField()),
                ('fees_rem', models.FloatField(default=0.0)),
                ('is_owing', models.BooleanField(default=False)),
                ('date_enrolled', models.DateField(default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('crech', 'crech'), ('lower_primary', 'lower_primary'), ('upper_primary', 'upper_primary'), ('jhs', 'jhs')], max_length=25)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.classroom')),
            ],
        ),
    ]
