# Generated by Django 4.2.5 on 2024-08-17 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('num_of_students', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(choices=[('crech', 'Crech / Kindergarten'), ('lower_primary', 'Lower primary'), ('upper_primary', 'Upper primary'), ('jhs', 'JHS')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('assigned_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='core.classroom', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(editable=False, max_length=100)),
                ('guardian_full_name', models.CharField(max_length=255)),
                ('guardian_phone_number', models.IntegerField()),
                ('guardian_relation', models.CharField(max_length=25)),
                ('fees_paid', models.FloatField()),
                ('fees_rem', models.FloatField(default=0.0)),
                ('is_owing', models.BooleanField(default=False)),
                ('date_enrolled', models.DateField(default=datetime.datetime.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.classroom', to_field='name')),
            ],
        ),
    ]
