# Generated by Django 5.0.6 on 2024-05-14 00:30

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('feesPaid', models.FloatField()),
                ('date_enrolled', models.DateTimeField(default=datetime.datetime.now)),
                ('classroom', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
            ],
        ),
    ]
