# Generated by Django 4.2.5 on 2024-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='category',
            field=models.CharField(choices=[('crech', 'Crech / Kindergarten'), ('lower_primary', 'Lower primary'), ('upper_primary', 'Upper primary'), ('jhs', 'JHS')], max_length=25),
        ),
    ]
