# Generated by Django 5.0.6 on 2024-05-14 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_date_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('num_of_students', models.IntegerField()),
                ('class_teacher', models.CharField(max_length=100)),
            ],
        ),
    ]
