# Generated by Django 5.0.6 on 2024-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='num_of_students',
            field=models.IntegerField(blank=True),
        ),
    ]
