# Generated by Django 5.0.6 on 2024-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_classroom_num_of_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='num_of_students',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
