# Generated by Django 5.0.6 on 2024-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='category',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
