# Generated by Django 5.0.6 on 2024-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_student_is_owing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_owing',
            field=models.BooleanField(default=False),
        ),
    ]
