# Generated by Django 5.0.6 on 2024-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_student_is_owing'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_rem',
            field=models.FloatField(default=0.0),
        ),
    ]
